name: Upload APK File

on:
  workflow_dispatch:
    inputs:
      apk_path:
        description: 'Path to the APK file'
        required: true

jobs:
  upload-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create file directory
      run: mkdir -p upload

    - name: Upload APK from local machine
      run: |
        echo "Upload your APK file to the runner"
        # This step is a placeholder where you will manually upload the file.
        # For example, using scp from local machine
        # scp /path/to/local/apk user@runner:/path/to/repo/upload/apk_file.apk
        touch upload/${{ github.event.inputs.apk_path }}

    - name: Echo contents of upload directory
      run: |
        echo "Contents of upload directory:"
        ls -l upload

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: apk-file
        path: upload/${{ github.event.inputs.apk_path }}
        
    - name: Echo contents of upload directory 
      run: |
        echo "Contents of upload directory  --->"
        ls -l upload    
