name: Use APK for Automation Testing

on:
  workflow_dispatch:
    inputs:
      apk_path:
        description: 'Path to the APK file in the repository'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set environment variable for APK path
      run: echo "APK_PATH=${{ github.event.inputs.apk_path }}" >> $GITHUB_ENV

    - name: List files in repository
      run: ls -l

    - name: Use APK for automation testing
      run: |
        echo "Running automation tests using the APK at $APK_PATH"
        # Example command for running tests:
        # ./gradlew connectedAndroidTest -PapkPath=$APK_PATH
        ls -l $APK_PATH  # Listing the APK file for demonstration purposes
