name: Download APK from Another Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Checkout APK branch
      uses: actions/checkout@v2
      with:
        ref: dumm  # Replace with the name of the branch where the APK is stored
        path: apk_branch_files  # This is the directory where the dash branch is checked out

    - name: Copy APK to upload directory
      run: |
        mkdir -p upload
        cp apk_branch_files/test.apk upload/  # Make sure this path matches the location of your APK file in the dash branch

    - name: Echo contents of upload directory
      run: |
        echo "Contents of upload directory:"
        ls upload
        pwd upload
