name: Upload APK File

on:
  workflow_dispatch:
    inputs:
      apk_path:
        description: 'Path to the APK file'
        required: true

jobs:
  upload-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create file directory
      run: mkdir -p upload

    - name: Upload APK from local machine (Placeholder)
      run: |
        echo "Creating a dummy APK file for demonstration"
        mkdir -p $(dirname upload/${{ github.event.inputs.apk_path }})
        touch upload/${{ github.event.inputs.apk_path }}
        echo "Dummy content" > upload/${{ github.event.inputs.apk_path }}

    - name: Echo contents of upload directory
      run: |
        echo "Contents of upload directory:"
        ls -l upload

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: apk-file
        path: upload/${{ github.event.inputs.apk_path }}

    - name: Echo contents of upload directory 2
      run: |
        echo "Contents of upload directory: 2"
        ls -l upload     
